name: C++ CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libglu1-mesa-dev libglm-dev libglfw3-dev libzstd-dev meson cmake libxml2-dev doxygen graphviz xsltproc libstdc++-12-dev libboost-all-dev docbook-xsl
        version: 1.0

    - uses: actions/checkout@v3

    - name: Cache Gtkmm4
      id: cache-gtkmm4
      uses: actions/cache@v3
      with:
        path: /usr/local/include/gtkmm-4.0
        key: ${{ runner.os }}-gtkmm4
        lookup-only: true

    - name: Build Gtkmm4
      if: steps.cache-gtkmm4.outputs.cache-hit != 'true'
      run: ./.gtkmm4.sh

    - name: make
      run: make -j
